version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - type: bind
        source: C:\\Users\\Y\\Documents\\hd\\2\\
        target: /etc/selenoid/
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    restart: always
    links:
      - selenoid
    ports:
      - "8082:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]