class RegistrationPageLocators:
    url_page = "/index.php?route=account/register"
    header_registration = "//div[@id='content']/h1"
    first_name = "//input[@id='input-firstname']"
    last_name = "//input[@id='input-lastname']"
    e_mail = "//input[@id='input-email']"
    telephone = "//input[@id='input-telephone']"
    password = "//input[@id='input-password']"
    password_confirm = "//input[@id='input-confirm']"
    privacy_policy = "//input[@type='checkbox']"
    button_continue = "//input[contains(@class,'btn-primary')]"
    header_success_registration = "//div/h1"
    popup_error_telephone = "//div[@class='col-sm-10']/input[@name='telephone']/following-sibling::div[@class='text-danger']"
    popup_error_password = "//div[@class='col-sm-10']/input[@name='password']/following-sibling::div[@class='text-danger']"
    popup_error_password_confirm = "//div[@class='col-sm-10']/input[@placeholder='Password Confirm']/following-sibling::div[@class='text-danger']"
